---
- name: my test playbook
  hosts: all
  become: true
  vars:
    users:
      - sai
      - hari
      - ravi

  tasks:
    - name: creating multi users
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"


