---
- name: Tomcat setup
  hosts: all
  become: true
  tasks:
    - name: Install Java on RedHat
      yum:
        name: java
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Java on Debian
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Download Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.tar.gz
        dest: /opt/apache-tomcat-11.0.2.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat-11.0.2.tar.gz
        dest: /opt
        remote_src: yes

    - name: Set file permissions on startup.sh
      file:
        path: /opt/apache-tomcat-11.0.2/bin/startup.sh
        mode: '0777'

    - name: Run  startup.sh file
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-11.0.2/bin











