---
- name: my test playbook
  hosts: all
  become: true
  tasks:
    - name: stop httpd services
      service:
        name: httpd
        state: stopped

    - name: Remove httpd package
      package:
        name: httpd
        state: absent


  

